# Generated by Django 5.1.6 on 2025-02-16 14:07

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_channel_options_alter_myuser_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='subscribers',
            field=models.ManyToManyField(blank=True, related_name='channels', to=settings.AUTH_USER_MODEL),
        ),
    ]
