# Generated by Django 5.1.6 on 2025-02-18 08:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='video',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='video_photos/'),
        ),
    ]
