# Generated by Django 5.1.6 on 2025-02-19 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_alter_video_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='like',
            name='like',
            field=models.BooleanField(default=None, null=True),
        ),
    ]
